### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Stakingsoup** [morawskim/phpmyadmin-curl-export#2]
hello ,do you understand how to export recursive all database from phpMyAdmin???.. because i have much ,table or database in my phpMyAdmin

**Comment by morawskim** [comment]
If you know all databases you can use a loop.

Simple example for bash:
```
for db in dbName1 dbName2 dbName3
do
	phpmyadmin-curl-export --auth-type=cookie --dbname=$db --phpmyadmin-user=example --phpmyadmin-password=example --host=http://localhost/phpMyAdmin
done
```

**Comment by Stakingsoup** [comment]
wow ,this is a very good idea, thank you sir
